---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploymentrecreate
  namespace: my-own
  labels:
    app: nginx-deploymentrecreate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploymentrecreate
  template:
    metadata:
      labels:
        app: nginx-deploymentrecreate
    spec:
      containers:
        - name: nginx
          image: adamtravis/rollouts:blue
          ports:
            - containerPort: 8080
 
 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-deployrecreate
  namespace: my-own
spec:
  type: NodePort
  selector:
    app: nginx-deploymentrecreate
  ports:
    - protocol: TCP
      port: 6008
      targetPort: 8080
